spring:
  task:
    pool:
      corePoolSize: 16
      maxPoolSize: 32
      keepAliveSeconds: 3000
      queueCapacity: 200

  redis:
    hostname: 10.252.18.31:26000,10.252.18.31:26001,10.252.18.31:26002,10.252.18.31:26003,10.252.18.31:26004,10.252.18.31:26005
    mode: cluster           # stand_alone, cluster, sentinel
    database: 0
    master4Sentinel:        # 哨兵模式(sentinel)时启用
    password: redis         # 默认为空
    pool:
      maxIdle: 200          # 最大空闲数
      maxTotal: 1000        # 控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
      maxWaitMillis: 5000   # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
      testOnBorrow: false   # 从池中取出连接时是否检验

remote:
  face-service:
    name: face-service
    url: 10.70.100.158:15006
    face-feature: /incoming/visit?policy=znv_tcp_camera
  heat-service:
    name: heat-service
    url: 10.252.18.33:5001
    queryHeatChart: /statistic/attribute_query
    heatcomputation: /heatcomputation
  sync-service:
    name: sync-service
    url: 10.252.18.33:5000
    sync-visitor: /mixed_data/solo_store
  gclib:
    name: gclib
    url: 10.252.18.33:5005
    fdb-portrait: /fdb/portrait
    store-person: /store/person

redis:                                              # 必要
  uniquekey:
    mac_key: macad_macid                            # mac地址与mac id 映射集合 (全局唯一)
    mac_key_max: macad_macid_max                    # mac当前id (新的mac自增)
    org_key: orgid_storeid                          # 店铺id与store_id 映射集合 (全局唯一)
    org_key_max: orgid_storeid_max                  # store 当前id (新的店铺自增)
    mac_key_image: mac_new_image                    # 每个mac_id 的最新图像