server:
  port: 8101
  context-path: /customer-identification-system
  max-http-header-size: 8192
  tomcat:
    accept-count: 5000
    max-connections: 30000
    max-threads: 5000
    uri-encoding: UTF-8
    min-spare-threads: 200
    accesslog:
      directory: /data/logs/
      enabled: false

management:
  context-path: /
  port: 9101
  security:
    enabled: false
  
spring:
  task: 
    pool:
      corePoolSize: 16
      maxPoolSize: 32
      keepAliveSeconds: 3000
      queueCapacity: 200
      
