spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyyMMdd HHmmss
server:
  port: 8101
  context-path: /customer-identification-system
  max-http-header-size: -1
nacos:
  config:
    server-addr: 192.168.10.102:8848
  discovery:
    server-addr: 192.168.10.102:8848
