management:
  context-path: /
  port: 9101
  security:
    enabled: false
  
spring:
  task: 
    pool:
      corePoolSize: 16
      maxPoolSize: 32
      keepAliveSeconds: 3000
      queueCapacity: 200
remote: 
  businessHall: 
    name: TestProject
    url: localhost:8102
    businessHall: /test/base/get/{name}
    businessHall1: /test/base/post
    businessHall2: /test/base/delete/{name}
  face-service:
    name: face-service
    url: localhost:8080
    face-feature: /v1/face/feature
  heat-service: 
    name: heat-service
    url: localhost:8080
    heatcomputation: /heatcomputation
  sync-service:
    name: sync-service
    url: localhost:8080
    sync-visitor: /sync/visitor
  gclib:
    name: gclib
    url: localhost:8080
    fdb-portrait: /fdb/portrait
    store-person: /store/person
    store-person-reset: /store/person/reset
    store-person-search: /store/person/search
    