spring:
  task:
    pool:
      corePoolSize: 16
      maxPoolSize: 32
      keepAliveSeconds: 3000
      queueCapacity: 200
nacos:
  config:
    server-addr: 192.168.10.102:8848
remote:
  businessHall:
    name: TestProject
    url: localhost:8102
    businessHall: /test/base/get/{name}
    businessHall1: /test/base/post
    businessHall2: /test/base/delete/{name}
  face-service:
    name: face-service
    url: 10.70.100.158:5001
    face-feature: incoming/visit?policy=znv_tcp_camera
  heat-service:
    name: heat-service
    url: localhost:8080
    heatcomputation: /heatcomputation
  sync-service:
    name: sync-service
    url: localhost:8080
    sync-visitor: mixed_data/solo_store
  gclib:
    name: gclib
    url: localhost:8080
    fdb-portrait: /fdb/portrait
    store-person: /store/person


