spring:
  task: 
    pool:
      corePoolSize: 16
      maxPoolSize: 32
      keepAliveSeconds: 3000
      queueCapacity: 200

token:
  login-url: http://admin.aihall.zj.chinamobile.com/api/users/login
#  login: /api/users/login
  login-username: aihall
  login-password: U2FsdGVkX19B5qA6zUQWvfAKeuEdh7zA5UewmqMCZf4=:::ngpU/GO7pA6O+lzBgIrcdQBaY68+kOnlKHiPQWbnVHxvLCjVUmNtllZlBViOwhSu8yY2CYOqx/O1s4lruxN0/SQVkABZgiGAZ6tYy7ZXPOboz/NF/JzESPzzlpuH31Q7S9/Bls1epTIP2JwJrzCkeiM0PEN7llOZcL0icHSCNW0=
  store-url: http://admin.aihall.zj.chinamobile.com/api/stores/find
  store-param: 11

remote: 
  businessHall: 
    name: TestProject
    url: localhost:8102
    businessHall: /test/base/get/{name}
    businessHall1: /test/base/post
    businessHall2: /test/base/delete/{name}
  face-service:
    name: face-service
    url: localhost:8102
    face-feature: /test/base/incoming/visit_on_group
  heat-service: 
    name: heat-service
    url: localhost:8080
    heatcomputation: /heatcomputation
  sync-service:
    name: sync-service
    url: localhost:8080
    sync-visitor: /sync/visitor
  gclib:
    name: gclib
    url: localhost:8080
    fdb-portrait: /fdb/portrait
    store-person: /store/person
    store-person-reset: /store/person/reset
    store-person-search: /store/person/search
    